"""

Revision ID: d359d4b6b1c4
Revises: 454a04e0b0bb
Create Date: 2022-01-06 19:00:34.453421

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'd359d4b6b1c4'
down_revision = '454a04e0b0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_line_items', sa.Column('decision', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_line_items', 'decision')
    # ### end Alembic commands ###
